[tool.poetry]
name = "open_pref_eval"
version = "0.1.0"
description = "Dead Simple Open LLM Preference Evaluation"
authors = ["wassname <github@wassname.org>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
transformers = "^4.43.2"
datasets = "^2.20.0"
trl = "^0.9.4"
pandas = "^2.2.0"
torch = "^2.3.0"
jaxtyping = "^0.2.19"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
ipywidgets = "^8.1.3"
tqdm = "^4.66.4"
loguru = "^0.7.2"
tabulate = "^0.9.0"
matplotlib = "^3.9.1"
pytest = "^8.3.2"
parameterized = "^0.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
